### ISSUE TITLE
Provide possibility to add and copy variables with attributes

### ISSUE THREAD

**Issue by OldFcuk** [BlueByteSystemsInc/PDMCLI-QA#2]
Creating variables is most times consuming work for admin. Being able to create new variables with attribues from batch file would be huge time saver.
Might be easier to copy variables that already have needed attributes. Attributes wold be renamed according to variable value.

**Comment by AmenJlili** [comment]
@OldFcuk : Possibly resolved by this ticket https://github.com/BlueByteSystemsInc/PDMCLI-QA/issues/7

**Comment by AmenJlili** [comment]
This done @OldFcuk : 
![image](https://user-images.githubusercontent.com/16106587/172962448-48149979-f367-4933-8271-4da2d969cce0.png)
