### ISSUE TITLE
Update process not completing

### ISSUE THREAD

**Issue by massimomagris** [BlueByteSystemsInc/PDMCLI-QA#8]
Hello, after downloading update, the dialog display 100% but it's stuck there. If closing and repair, It keep asking for update. How to fix? Thanks, regards Massimo

**Comment by massimomagris** [comment]
As a workaround, I removed the previous and installed the latest version "manually"

**Comment by massimomagris** [comment]
Proposal: Add a request to user if want to upgrade or run the current version.
Also if possible to have a "settign" that disable the update check.
Thanks, regards

**Comment by AmenJlili** [comment]
@massimomagris : I have reverted the changes...

**Comment by AmenJlili** [comment]
This has been fixed.
